// HF14 LMSR Q96 vector-parity test — the #1 consensus merge gate.
//
// Loads the frozen normative vector file (generated by reference/lmsr_fixed.php, GMP) and
// asserts the C++ port reproduces every value with STRICT equality (no tolerance). A single
// mismatch is a fork risk. This MUST pass on every supported toolchain (MSVC / UCRT64 / Linux)
// BEFORE the PM evaluators are trusted. See lmsr-fixed-point-spec.md §5.

#define BOOST_TEST_MODULE pm_lmsr_vectors
#include <boost/test/unit_test.hpp>

#include <graphene/chain/pm/lmsr_q96.hpp>

#include <fc/io/json.hpp>
#include <fc/variant.hpp>
#include <fc/filesystem.hpp>

#include <string>
#include <vector>

using namespace graphene::chain::lmsr;
using graphene::chain::lmsr::q96;

#ifndef LMSR_VECTORS_JSON
#error "LMSR_VECTORS_JSON path must be defined by CMake"
#endif

namespace {

    fc::variant load_vectors() {
        return fc::json::from_file(fc::path(std::string(LMSR_VECTORS_JSON)));
    }

    q96 to_q96(const fc::variant& v) { return q96(v.as_string()); }

    std::vector<int64_t> to_i64_vec(const fc::variant& v) {
        std::vector<int64_t> out;
        for (const auto& e : v.get_array()) out.push_back(e.as_int64());
        return out;
    }

    std::string s(const q96& x) { return x.str(); }

} // namespace

BOOST_AUTO_TEST_SUITE(pm_lmsr_vectors)

BOOST_AUTO_TEST_CASE(constants_match) {
    auto V = load_vectors();
    const auto& c = V["constants"];
    BOOST_CHECK_EQUAL(s(q96(1) << 96), c["ONE"].as_string());
    BOOST_CHECK_EQUAL(c["LN2"].as_string(), std::string("54916777467707473351141471128"));
}

BOOST_AUTO_TEST_CASE(mul_q_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["mul_q"].get_array()) {
        auto o = t;
        q96 got = detail::mul_q(to_q96(o["a"]), to_q96(o["b"]));
        BOOST_CHECK_EQUAL(s(got), o["expected"].as_string());
    }
}

BOOST_AUTO_TEST_CASE(div_q_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["div_q"].get_array()) {
        auto o = t;
        q96 got = detail::div_q(to_q96(o["a"]), to_q96(o["b"]));
        BOOST_CHECK_EQUAL(s(got), o["expected"].as_string());
    }
}

BOOST_AUTO_TEST_CASE(exp_q_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["exp_q"].get_array()) {
        auto o = t;
        q96 got = detail::exp_q(to_q96(o["x"]));
        BOOST_CHECK_EQUAL(s(got), o["expected"].as_string());
    }
}

BOOST_AUTO_TEST_CASE(ln_q_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["ln_q"].get_array()) {
        auto o = t;
        q96 got = detail::ln_q(to_q96(o["x"]));
        BOOST_CHECK_EQUAL(s(got), o["expected"].as_string());
    }
}

BOOST_AUTO_TEST_CASE(lmsr_cost_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["lmsr_cost"].get_array()) {
        auto o = t;
        int64_t got = lmsr_cost(to_i64_vec(o["q"]), o["b"].as_int64());
        BOOST_CHECK_EQUAL(got, o["expected"].as_int64());
    }
}

BOOST_AUTO_TEST_CASE(lmsr_prices_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["lmsr_prices"].get_array()) {
        auto o = t;
        auto got = lmsr_prices(to_i64_vec(o["q"]), o["b"].as_int64());
        auto exp = to_i64_vec(o["expected"]);
        BOOST_REQUIRE_EQUAL(got.size(), exp.size());
        for (size_t i = 0; i < exp.size(); ++i) BOOST_CHECK_EQUAL(got[i], exp[i]);
    }
}

BOOST_AUTO_TEST_CASE(lmsr_buy_cost_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["lmsr_buy_cost"].get_array()) {
        auto o = t;
        int64_t got = lmsr_buy_cost(to_i64_vec(o["q"]), o["b"].as_int64(),
                                    (int)o["i"].as_int64(), o["delta"].as_int64());
        BOOST_CHECK_EQUAL(got, o["expected"].as_int64());
    }
}

BOOST_AUTO_TEST_CASE(lmsr_sell_return_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["lmsr_sell_return"].get_array()) {
        auto o = t;
        int64_t got = lmsr_sell_return(to_i64_vec(o["q"]), o["b"].as_int64(),
                                       (int)o["i"].as_int64(), o["delta"].as_int64());
        BOOST_CHECK_EQUAL(got, o["expected"].as_int64());
    }
}

BOOST_AUTO_TEST_CASE(lmsr_tokens_for_amount_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["lmsr_tokens_for_amount"].get_array()) {
        auto o = t;
        int64_t got = lmsr_tokens_for_amount(to_i64_vec(o["q"]), o["b"].as_int64(),
                                             (int)o["i"].as_int64(), o["amount"].as_int64());
        BOOST_CHECK_EQUAL(got, o["expected"].as_int64());
    }
}

BOOST_AUTO_TEST_CASE(lmsr_b_from_liquidity_vectors) {
    auto V = load_vectors();
    for (const auto& t : V["lmsr_b_from_liquidity"].get_array()) {
        auto o = t;
        int64_t got = lmsr_b_from_liquidity(o["liquidity"].as_int64(), (int)o["n"].as_int64());
        BOOST_CHECK_EQUAL(got, o["expected"].as_int64());
    }
}

BOOST_AUTO_TEST_SUITE_END()
