FROM phusion/baseimage:noble-1.0.3 AS builder

ENV LANG=en_US.UTF-8
ENV APPDIR=/usr/local/src/viz/
ENV HOME=/var/lib/vizd

RUN \
    for i in 1 2 3; do \
        apt-get update && \
        apt-get install -y --no-install-recommends \
            autoconf \
            automake \
            autotools-dev \
            binutils \
            bsdmainutils \
            build-essential \
            cmake \
            git \
            ccache \
            libboost-chrono-dev \
            libboost-context-dev \
            libboost-coroutine-dev \
            libboost-date-time-dev \
            libboost-filesystem-dev \
            libboost-iostreams-dev \
            libboost-locale-dev \
            libboost-program-options-dev \
            libboost-serialization-dev \
            libboost-system-dev \
            libboost-test-dev \
            libboost-thread-dev \
            libbz2-dev \
            liblzma-dev \
            libzstd-dev \
            libreadline-dev \
            libssl-dev \
            libtool \
            ncurses-dev \
            pbzip2 \
            pkg-config \
            zlib1g-dev && \
        break || sleep 10; \
    done && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Explicitly copy needed files to avoid re-building when changing other files
COPY .git $APPDIR/.git
COPY .gitignore .gitmodules CMakeLists.txt Doxyfile $APPDIR/
COPY programs $APPDIR/programs
COPY thirdparty $APPDIR/thirdparty
COPY plugins $APPDIR/plugins
COPY libraries $APPDIR/libraries

RUN \
    cd $APPDIR && \
    git submodule update --init --recursive -f && \
    mkdir build && \
    cd build && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBRARIES=FALSE \
        -DLOW_MEMORY_NODE=FALSE \
        -DCHAINBASE_CHECK_LOCKING=FALSE \
        -DENABLE_MONGO_PLUGIN=FALSE \
        .. \
    && \
    make -j$(nproc)

RUN set -xe ;\
    cd $APPDIR/build ;\
    make install ;\
    rm -rf $APPDIR

RUN \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/*

FROM phusion/baseimage:noble-1.0.3 AS production
COPY --from=builder /usr/local /usr/local

RUN set -xe ;\
    useradd -s /bin/bash -m -d /var/lib/vizd vizd ;\
    mkdir /var/cache/vizd ;\
    chown vizd:vizd -R /var/cache/vizd

COPY share/vizd/vizd.sh /etc/service/vizd/run
COPY share/vizd/snapshot.json /var/lib/vizd
COPY share/vizd/config/config.ini /etc/vizd/config.ini
COPY share/vizd/seednodes /etc/vizd/seednodes

# rpc services:
# http
EXPOSE 8090
# ws
EXPOSE 8091
# p2p service:
EXPOSE 2001

VOLUME ["/var/lib/vizd", "/etc/vizd"]
