#include <graphene/protocol/operations.hpp>

#include <graphene/protocol/operation_util_impl.hpp>

#include <type_traits>

namespace graphene {
    namespace protocol {

        struct is_vop_visitor {
            typedef bool result_type;

            template<typename T>
            bool operator()(const T &v) const {
                return v.is_virtual();
            }
        };

        bool is_virtual_operation(const operation &op) {
            return op.visit(is_vop_visitor());
        }

        struct is_dop_visitor {
            typedef bool result_type;

            template<typename T>
            bool operator()(const T &v) const {
                return false;
            }

            bool operator()(const custom_operation&) const {
                return true;
            }

            bool operator()(const account_create_operation&) const {
                return true;
            }

            bool operator()(const account_update_operation&) const {
                return true;
            }

            bool operator()(const account_metadata_operation&) const {
                return true;
            }

            bool operator()(const escrow_transfer_operation&) const {
                return true;
            }
        };

        bool is_data_operation(const operation &op) {
            return op.visit(is_dop_visitor());
        }

        // Wire name of an operation, i.e. what the client writes as the first element of an
        // operation array: `graphene::protocol::transfer_operation` -> `transfer`.
        struct op_wire_name_visitor {
            typedef std::string result_type;

            template<typename T>
            std::string operator()(const T &) const {
                return fc::name_from_type(fc::get_typename<T>::name());
            }
        };

        // Compile-time classification: the visitor never reads the visited object, which matters
        // because the enumeration below visits default-constructed variants tagged via set_which()
        // (the same pattern DEFINE_OPERATION_TYPE uses). A runtime is_virtual() call would touch a
        // member of an object that was never constructed as that alternative.
        struct op_virtual_type_visitor {
            typedef bool result_type;

            template<typename T>
            bool operator()(const T &) const {
                return std::is_base_of<virtual_operation, T>::value;
            }
        };

        std::string operation_wire_name(const operation &op) {
            return op.visit(op_wire_name_visitor());
        }

        const flat_set<std::string> &broadcastable_operation_wire_names() {
            static const flat_set<std::string> names = []() {
                flat_set<std::string> s;
                for (int i = 0; i < operation::count(); ++i) {
                    operation tmp;
                    tmp.set_which(i);
                    if (tmp.visit(op_virtual_type_visitor()))
                        continue; // virtual operations are generated by the chain, never broadcast
                    s.insert(tmp.visit(op_wire_name_visitor()));
                }
                return s;
            }();
            return names;
        }

        bool is_broadcastable_operation_wire_name(const std::string &name) {
            return broadcastable_operation_wire_names().count(name) > 0;
        }

    }
} // graphene::protocol

DEFINE_OPERATION_TYPE(graphene::protocol::operation)
