#pragma once

#include <graphene/protocol/base.hpp>
#include <graphene/protocol/block_header.hpp>
#include <graphene/protocol/asset.hpp>

namespace graphene { namespace protocol {

        // HF14 Prediction-Market virtual operations: deterministic, block-generated by the
        // bounded per-block cron in database_pm.cpp. They derive from virtual_operation, so
        // is_virtual_operation() returns true automatically (no manual registration needed).

        using pm_vop_object_id_type = int64_t;

        /// Epoch-boundary batch settlement of queued/revealed bets at a uniform price.
        struct pm_batch_settle_operation : public virtual_operation {
            pm_batch_settle_operation() {}
            pm_batch_settle_operation(pm_vop_object_id_type m, uint32_t e, uint32_t n)
                : market_id(m), epoch(e), settled_bets(n) {}

            pm_vop_object_id_type market_id = 0;
            uint32_t              epoch = 0;
            uint32_t              settled_bets = 0;
        };

        /// Unrevealed commitment forfeits its penalty into the market's forfeit_pool.
        struct pm_commit_forfeit_operation : public virtual_operation {
            pm_commit_forfeit_operation() {}
            pm_commit_forfeit_operation(const account_name_type& a, pm_vop_object_id_type c,
                                        pm_vop_object_id_type m, const asset& p, const asset& r)
                : account(a), commit_id(c), market_id(m), penalty(p), refund(r) {}

            account_name_type     account;
            pm_vop_object_id_type commit_id = 0;
            pm_vop_object_id_type market_id = 0;
            asset                 penalty;   ///< -> market.forfeit_pool
            asset                 refund;    ///< returned to account
        };

        /// Deferred payout credited to a winner after the dispute grace elapsed.
        struct pm_auto_payout_operation : public virtual_operation {
            pm_auto_payout_operation() {}
            pm_auto_payout_operation(const account_name_type& a, pm_vop_object_id_type m,
                                     pm_vop_object_id_type b, const asset& p)
                : account(a), market_id(m), bet_id(b), payout(p) {}

            account_name_type     account;
            pm_vop_object_id_type market_id = 0;
            pm_vop_object_id_type bet_id = 0;
            asset                 payout;
        };

        /// A dispute was filed against a resolved market. Carries the `oracle` (and `disputer`)
        /// so the event lands in BOTH their account histories — the oracle's timeline shows
        /// "a dispute was opened against my resolution", not just the disputer's side.
        struct pm_dispute_opened_operation : public virtual_operation {
            pm_dispute_opened_operation() {}
            pm_dispute_opened_operation(const account_name_type& orc, const account_name_type& disp,
                                        pm_vop_object_id_type m, int16_t po)
                : oracle(orc), disputer(disp), market_id(m), proposed_outcome(po) {}

            account_name_type     oracle;
            account_name_type     disputer;
            pm_vop_object_id_type market_id = 0;
            int16_t               proposed_outcome = -1;
        };

        /// Committee-mode tally finalized at voting_end_time. Carries `oracle` so the verdict
        /// (and any penalty) is visible in the oracle's own account history.
        struct pm_dispute_finalize_operation : public virtual_operation {
            pm_dispute_finalize_operation() {}
            pm_dispute_finalize_operation(const account_name_type& orc, pm_vop_object_id_type m,
                                          int16_t o, const asset& p)
                : oracle(orc), market_id(m), winning_outcome(o), oracle_penalty(p) {}

            account_name_type     oracle;
            pm_vop_object_id_type market_id = 0;
            int16_t               winning_outcome = -1;
            asset                 oracle_penalty;
        };

        /// Anti-freeze fallback: dispute unresolved at auto_close_time -> full refund.
        /// Carries `oracle` so the auto-close (and its penalty) shows in the oracle's history.
        struct pm_dispute_auto_close_operation : public virtual_operation {
            pm_dispute_auto_close_operation() {}
            pm_dispute_auto_close_operation(const account_name_type& orc, pm_vop_object_id_type m,
                                            const asset& p)
                : oracle(orc), market_id(m), oracle_penalty(p) {}

            account_name_type     oracle;
            pm_vop_object_id_type market_id = 0;
            asset                 oracle_penalty;
        };

        /// Oracle missed result_expiration -> slash insurance, refund all.
        struct pm_oracle_missed_penalty_operation : public virtual_operation {
            pm_oracle_missed_penalty_operation() {}
            pm_oracle_missed_penalty_operation(const account_name_type& o, pm_vop_object_id_type m, const asset& s)
                : oracle(o), market_id(m), slashed(s) {}

            account_name_type     oracle;
            pm_vop_object_id_type market_id = 0;
            asset                 slashed;
        };

        /// Lazy-pool graduated recall step (idle market allocation returned to free_balance).
        struct pm_lazy_recall_operation : public virtual_operation {
            pm_lazy_recall_operation() {}
            pm_lazy_recall_operation(pm_vop_object_id_type m, const asset& r)
                : market_id(m), recalled(r) {}

            pm_vop_object_id_type market_id = 0;
            asset                 recalled;
        };

        /// A leveraged position force-closed by the protocol (opposing bet / cancel-bet / expiration).
        struct pm_leverage_liquidate_operation : public virtual_operation {
            pm_leverage_liquidate_operation() {}
            pm_leverage_liquidate_operation(const account_name_type& a, pm_vop_object_id_type p,
                                            pm_vop_object_id_type m, const asset& cv,
                                            const asset& pr, const asset& br, uint8_t r)
                : account(a), position_id(p), market_id(m), cancel_value(cv),
                  pool_received(pr), bettor_received(br), reason(r) {}

            account_name_type     account;
            pm_vop_object_id_type position_id = 0;
            pm_vop_object_id_type market_id = 0;
            asset                 cancel_value;
            asset                 pool_received;
            asset                 bettor_received;
            uint8_t               reason = 0; ///< 0 opposing_bet, 1 cancel_bet, 2 expiration
        };

        /// Market launched: the oracle accepted (or a self-oracle auto-accepted at creation),
        /// freezing the agreed oracle terms onto the market. Lets history-parsing scripts react
        /// that the market moved from pending to active and on what terms.
        struct pm_market_accepted_operation : public virtual_operation {
            pm_market_accepted_operation() {}
            pm_market_accepted_operation(const account_name_type& o, const account_name_type& c,
                                         pm_vop_object_id_type m, uint16_t fp, const asset& ff, bool self)
                : oracle(o), creator(c), market_id(m),
                  oracle_fee_percent(fp), oracle_fixed_fee(ff), self_oracle(self) {}

            account_name_type     oracle;
            account_name_type     creator;
            pm_vop_object_id_type market_id = 0;
            uint16_t              oracle_fee_percent = 0; ///< frozen oracle % (bp, 10000=100%)
            asset                 oracle_fixed_fee;       ///< frozen oracle fixed fee
            bool                  self_oracle = false;    ///< true = auto-accepted at creation
        };

        /// A leveraged position settled at market resolution (force-closed at the final reserves).
        /// `won` = the position was solvent (cancel_value >= obligation, so the bettor got money back);
        /// `bettor_received == 0` ⇒ a negative outcome (collateral lost). `leverage` is the integer
        /// multiple total_bet/collateral (e.g. 10 for ×10).
        struct pm_leverage_resolve_operation : public virtual_operation {
            pm_leverage_resolve_operation() {}
            pm_leverage_resolve_operation(const account_name_type& a, pm_vop_object_id_type p,
                                          pm_vop_object_id_type m, bool w,
                                          const asset& pr, const asset& br,
                                          int16_t oi, uint16_t lev)
                : account(a), position_id(p), market_id(m), won(w),
                  pool_received(pr), bettor_received(br), outcome_index(oi), leverage(lev) {}

            account_name_type     account;
            pm_vop_object_id_type position_id = 0;
            pm_vop_object_id_type market_id = 0;
            bool                  won = false;
            asset                 pool_received;
            asset                 bettor_received;
            int16_t               outcome_index = 0;  ///< side/outcome the position was on
            uint16_t              leverage = 0;       ///< total_bet / collateral (integer multiple)
        };

        /// Per-bettor settlement of a parimutuel market: the bet's stake, the side/outcome it was on,
        /// and the realized payout (`0` on a loss). Emitted once per active bet inside settle_market,
        /// alongside the single market-level pm_auto_payout marker.
        struct pm_payout_operation : public virtual_operation {
            pm_payout_operation() {}
            pm_payout_operation(const account_name_type& a, pm_vop_object_id_type m, pm_vop_object_id_type b,
                                int8_t s, int16_t oi, const asset& amt, const asset& p)
                : account(a), market_id(m), bet_id(b), side(s), outcome_index(oi), amount(amt), payout(p) {}

            account_name_type     account;
            pm_vop_object_id_type market_id = 0;
            pm_vop_object_id_type bet_id = 0;
            int8_t                side = -1;          ///< binary: 0/1; multi: -1
            int16_t               outcome_index = -1; ///< multi: 0..N-1; binary: -1
            asset                 amount;             ///< the stake
            asset                 payout;             ///< credited at settle (0 on a loss)
        };

        /// Acceptance window expired: the named oracle neither accepted nor rejected a pending market
        /// within pm_oracle_accept_window_sec. The cron voids the market (status -1) and refunds the
        /// creator's seed liquidity — the non-refundable creation fee already went to the DAO fund at
        /// creation and is NOT returned. Distinct from an explicit oracle reject (a signed op).
        struct pm_market_expired_operation : public virtual_operation {
            pm_market_expired_operation() {}
            pm_market_expired_operation(const account_name_type& o, const account_name_type& c,
                                        pm_vop_object_id_type m, const asset& r)
                : oracle(o), creator(c), market_id(m), refunded_liquidity(r) {}

            account_name_type     oracle;
            account_name_type     creator;
            pm_vop_object_id_type market_id = 0;
            asset                 refunded_liquidity; ///< seed returned to creator (creation fee NOT refunded)
        };

        /// A temporary oracle and/or creator ban lapsed (now >= banned_until): the per-block cron
        /// cleared it and emits this so history/indexers observe the lift. An *early* manual lift is
        /// the signed pm_unban op instead (already visible in history), so this fires only for
        /// automatic time-expiry.
        struct pm_ban_expired_operation : public virtual_operation {
            pm_ban_expired_operation() {}
            pm_ban_expired_operation(const account_name_type& a, bool o, bool c)
                : account(a), oracle(o), creator(c) {}

            account_name_type account;
            bool              oracle = false;   ///< an oracle ban expired
            bool              creator = false;  ///< a creator ban expired
        };

        /// F1/#300: an early-exit deferred claim was paid at settlement. An early bet-cancel or
        /// leverage-close on the WINNING outcome draws from the bounded early-exit bucket
        /// (pm_early_exit_reward_cap_percent × losers_sum), FIFO by exit order. `claimed` is the
        /// full outcome-contingent claim that was recorded at exit; `paid` is what the bucket could
        /// actually fund (paid ≤ claimed — a shortfall is a haircut once the slice is exhausted).
        /// Emitting this puts the credit in the early-exiter's account history (adjust_balance alone
        /// leaves no trace) and lets indexers reconcile the settlement's token flow.
        struct pm_early_exit_claim_paid_operation : public virtual_operation {
            pm_early_exit_claim_paid_operation() {}
            pm_early_exit_claim_paid_operation(const account_name_type& a, pm_vop_object_id_type m,
                                               uint8_t k, uint8_t o, const asset& c, const asset& p)
                : account(a), market_id(m), kind(k), outcome_index(o), claimed(c), paid(p) {}

            account_name_type     account;
            pm_vop_object_id_type market_id = 0;
            uint8_t               kind = 0;          ///< 0 = bet cancel, 1 = leverage close/liquidate
            uint8_t               outcome_index = 0; ///< the winning outcome this claim was contingent on
            asset                 claimed;           ///< full claim recorded at exit
            asset                 paid;              ///< amount the bounded bucket funded (≤ claimed)
        };

        /// Settlement-time LP return (goal #442 / q#681=D). Each direct market LP's principal is
        /// returned unconditionally and they earn `income` — the market's liquidity fee + the
        /// late-bet time-penalty pool + undistributed winners dust, split across LPs by amount·time
        /// (pm::distribute_lp). `charge` is the F1/#300 uncovered shortfall withheld from that LP's
        /// principal (0 normally). Emitted once per active LP row inside settle_liquidity so LP
        /// income is finally visible in account_history — adjust_balance alone leaves no trace and
        /// today the income is not reconstructable. Lazy-pool allocations (empty provider) return to
        /// the pool's free_balance instead and do NOT emit this vop; their share of the market's
        /// income is covered by the market-level `liquidity_fee_earned` counter.
        struct pm_lp_payout_operation : public virtual_operation {
            pm_lp_payout_operation() {}
            pm_lp_payout_operation(const account_name_type& a, pm_vop_object_id_type m,
                                   const asset& pr, const asset& inc, const asset& chr)
                : account(a), market_id(m), principal(pr), income(inc), charge(chr) {}

            account_name_type     account;
            pm_vop_object_id_type market_id = 0;
            asset                 principal;  ///< committed principal returned (net of `charge`)
            asset                 income;     ///< LP bonus earned: liq_fee + time-penalty + dust
            asset                 charge;     ///< F1 uncovered shortfall charged against principal
        };

} } // graphene::protocol

FC_REFLECT((graphene::protocol::pm_batch_settle_operation), (market_id)(epoch)(settled_bets))
FC_REFLECT((graphene::protocol::pm_commit_forfeit_operation), (account)(commit_id)(market_id)(penalty)(refund))
FC_REFLECT((graphene::protocol::pm_auto_payout_operation), (account)(market_id)(bet_id)(payout))
FC_REFLECT((graphene::protocol::pm_dispute_opened_operation), (oracle)(disputer)(market_id)(proposed_outcome))
FC_REFLECT((graphene::protocol::pm_dispute_finalize_operation), (oracle)(market_id)(winning_outcome)(oracle_penalty))
FC_REFLECT((graphene::protocol::pm_dispute_auto_close_operation), (oracle)(market_id)(oracle_penalty))
FC_REFLECT((graphene::protocol::pm_oracle_missed_penalty_operation), (oracle)(market_id)(slashed))
FC_REFLECT((graphene::protocol::pm_lazy_recall_operation), (market_id)(recalled))
FC_REFLECT((graphene::protocol::pm_leverage_liquidate_operation),
    (account)(position_id)(market_id)(cancel_value)(pool_received)(bettor_received)(reason))
FC_REFLECT((graphene::protocol::pm_leverage_resolve_operation),
    (account)(position_id)(market_id)(won)(pool_received)(bettor_received)(outcome_index)(leverage))
FC_REFLECT((graphene::protocol::pm_market_accepted_operation),
    (oracle)(creator)(market_id)(oracle_fee_percent)(oracle_fixed_fee)(self_oracle))
FC_REFLECT((graphene::protocol::pm_payout_operation),
    (account)(market_id)(bet_id)(side)(outcome_index)(amount)(payout))
FC_REFLECT((graphene::protocol::pm_market_expired_operation),
    (oracle)(creator)(market_id)(refunded_liquidity))
FC_REFLECT((graphene::protocol::pm_ban_expired_operation),
    (account)(oracle)(creator))
FC_REFLECT((graphene::protocol::pm_early_exit_claim_paid_operation),
    (account)(market_id)(kind)(outcome_index)(claimed)(paid))
FC_REFLECT((graphene::protocol::pm_lp_payout_operation),
    (account)(market_id)(principal)(income)(charge))
