name: Build docker image for a PR

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - '**.md'

jobs:
  build:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./share/vizd/docker/Dockerfile-production
          push: true
          tags: vizblockchain/vizd:${{ github.head_ref }}
